CREATE TABLE Flights 
(cust_id INT, 
flight_id VARCHAR(10),
origin VARCHAR(50),
destination VARCHAR(50));


INSERT INTO Flights
(cust_id, flight_id, origin, destination)
VALUES 
(1, 'SG1234', 'Delhi', 'Hyderabad'),
(1, 'SG3476', 'Kochi', 'Mangalore'),
(1, '69876', 'Hyderabad', 'Kochi'),
(2, '68749', 'Mumbai', 'Varanasi'),
(2, 'SG5723', 'Varanasi', 'Delhi');


SELECT * FROM FLIGHTS

WITH ORIGIN AS
(SELECT F1.CUST_ID,
	   F1.ORIGIN
FROM FLIGHTS F1
LEFT JOIN 
FLIGHTS F2
ON F1.CUST_ID=F2.CUST_ID
AND F1.ORIGIN=F2.DESTINATION
WHERE F2.ORIGIN IS NULL),
DESTINATION AS
(SELECT F1.CUST_ID,
       F1.DESTINATION
FROM FLIGHTS F1
LEFT JOIN
FLIGHTS F2
ON F1.CUST_ID=F2.CUST_ID
AND F1.DESTINATION=F2.ORIGIN
WHERE F2.DESTINATION IS NULL)
SELECT O.CUST_ID,
	   O.ORIGIN,
	   D.DESTINATION
FROM ORIGIN O
INNER JOIN DESTINATION D
ON O.CUST_ID=D.CUST_ID
ORDER BY 1